openapi: 3.0.1
info:
  title: examples/internal/proto/examplepb/generate_unbound_methods.proto
  description: |-
    Generate Unannotated Methods Echo Service
    Similar to echo_service.proto but without annotations and without external configuration.

    Generate Unannotated Methods Echo Service API consists of a single service which returns
    a message.
  version: version not set
servers:
- url: /
paths:
  /grpc.gateway.examples.internal.examplepb.GenerateUnboundMethodsEchoService/Echo:
    post:
      tags:
      - GenerateUnboundMethodsEchoService
      summary: Echo method receives a simple message and returns it.
      description: |-
        The message posted as the id parameter will also be
        returned.
      operationId: GenerateUnboundMethodsEchoService_Echo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/examplepbGenerateUnboundMethodsSimpleMessage'
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplepbGenerateUnboundMethodsSimpleMessage'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      x-codegen-request-body-name: body
  /grpc.gateway.examples.internal.examplepb.GenerateUnboundMethodsEchoService/EchoBody:
    post:
      tags:
      - GenerateUnboundMethodsEchoService
      summary: EchoBody method receives a simple message and returns it.
      operationId: GenerateUnboundMethodsEchoService_EchoBody
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/examplepbGenerateUnboundMethodsSimpleMessage'
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplepbGenerateUnboundMethodsSimpleMessage'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      x-codegen-request-body-name: body
  /grpc.gateway.examples.internal.examplepb.GenerateUnboundMethodsEchoService/EchoDelete:
    post:
      tags:
      - GenerateUnboundMethodsEchoService
      summary: EchoDelete method receives a simple message and returns it.
      operationId: GenerateUnboundMethodsEchoService_EchoDelete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/examplepbGenerateUnboundMethodsSimpleMessage'
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplepbGenerateUnboundMethodsSimpleMessage'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      x-codegen-request-body-name: body
components:
  schemas:
    examplepbGenerateUnboundMethodsSimpleMessage:
      type: object
      properties:
        id:
          type: string
          description: Id represents the message identifier.
        num:
          type: string
          format: int64
        duration:
          type: string
      description: GenerateUnboundMethodsSimpleMessage represents a simple message
        sent to the unannotated GenerateUnboundMethodsEchoService service.
      example:
        duration: duration
        num: num
        id: id
    protobufAny:
      type: object
      properties:
        type_url:
          type: string
        value:
          pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
          type: string
          format: byte
    runtimeError:
      type: object
      properties:
        error:
          type: string
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
